worker_processes auto;

error_log logs/error.log;
pid logs/nginx.pid;

events {
    worker_connections 2048;
}

http {
    server {
        listen 8080;
        server_name localhost 127.0.0.1;
        root html;
        index index.html index.htm;

        location = /health {
            return 200 "ok";
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}

