worker_processes auto;

error_log logs/error.log;
pid logs/nginx.pid;

events {
    worker_connections 4096;
}

stream {
    proxy_connect_timeout 3s;
    proxy_timeout 12h;
    proxy_next_upstream error timeout;
    proxy_next_upstream_tries 3;
    proxy_next_upstream_timeout 10s;

    upstream tcp_backend {
        least_conn;
        server 192.168.0.100:22 max_fails=2 fail_timeout=10s;
        server 192.168.0.101:22 backup;
    }

    server {
        listen 2222;
        proxy_pass tcp_backend;
    }

    upstream udp_backend {
        server 192.168.0.100:15000;
        server 192.168.0.101:15000 backup;
    }

    server {
        listen 5353 udp;
        proxy_pass udp_backend;
        proxy_timeout 5s;
        proxy_responses 1;
    }
}

