worker_processes auto;

error_log logs/error.log error;
pid logs/nginx.pid;

events {
    worker_connections 16384;
    multi_accept on;
}

stream {
    proxy_connect_timeout 3s;
    proxy_timeout 12h;
    proxy_next_upstream error timeout;
    proxy_next_upstream_tries 3;
    proxy_next_upstream_timeout 10s;

    include conf.d/stream.generated/*.conf;
}

http {
    include mime.types;
    default_type application/octet-stream;

    server_names_hash_bucket_size 128;
    server_tokens off;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    keepalive_timeout 75s;
    keepalive_requests 10000;
    client_body_timeout 60s;
    client_header_timeout 30s;
    send_timeout 60s;

    reset_timedout_connection on;
    ignore_invalid_headers on;
    open_file_cache_errors off;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:50m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_connect_timeout 3s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;
    proxy_buffering on;
    proxy_buffers 32 64k;
    proxy_buffer_size 64k;
    client_max_body_size 1000m;

    include conf.d/http.generated/*.conf;

    server {
        listen 80 default_server;
        server_name _;
        return 301 https://$host$request_uri;
    }
}

